### ISSUE TITLE
success page after registration

### ISSUE THREAD

**Issue by ellipee** [hrevert/HtUserRegistration#22]
Hello, thank you for this wonderful module. i am a new zf2 user please i need help on how to achieve the following
1. users are directed to a registration success page telling them to check their email for confirmation after  each registration
2.when users confirm their registration, an event should change the state of the user and the role. a confirmation success page should display and tell the user to login into their account.

thank you very much in anticipation of your quick responds

**Comment by ojhaujjwal** [comment]
Please do some research before creating an issue.
