### ISSUE TITLE
users can login without confirmation

### ISSUE THREAD

**Issue by ellipee** [hrevert/HtUserRegistration#23]
i create a test registration and to my surprise i was able to login without confirming the registration email. how do i solve this issue

**Comment by ojhaujjwal** [comment]
As stated in the docs, you need to add an authentication adapter! Something like this:

``` php
return [
    'zfcuser' => [
        'auth_adapters' => [80 => 'HtUserRegistration\Authentication\Adapter\EmailVerification']
    ]
];
```

**Comment by ellipee** [comment]
please bear with me i am a newbie to zf2. i dont know where to put the above code, i put it into Module.php of htuseregistration module but it did not work
