### ISSUE TITLE
ZfcUserDependency

### ISSUE THREAD

**Issue by stijnhau** [hrevert/HtUserRegistration#5]
The modules doesn't work with ZfcUser 1.*
Change composer.json file pleas.

**Comment by ojhaujjwal** [comment]
Thanks, I will change that.

**Comment by ojhaujjwal** [comment]
Fixed in 89df8984a0b10555c4fe8fb5a692ff70f0854330

**Comment by stijnhau** [comment]
Oke thanks, will test it as sonn as i got time.
