### ISSUE TITLE
Got call to undefined method error

### ISSUE THREAD

**Issue by fabwu** [hrevert/HtUserRegistration#9]
I tried to install HtUserRegistration but I got the following error:

`Fatal error: Call to undefined method HtUserRegistration\Service\UserRegistrationService::getServiceLocator() in C:\xampp\htdocs\vendor\hrevert\ht-user-registration\src\Service\UserRegistrationService.php on line 79`

Is this a bug or have I made a mistake during the installation?

**Comment by ojhaujjwal** [comment]
I have not released stable version of this module. So, there may be bugs. Yes, this is a problem with this module. Thanks for informing me.

Do you mind doing a PR? The problem is simple.

**Comment by ojhaujjwal** [comment]
If you fix this error and if you didn't find any other bugs, I will tag 0.0.1

**Comment by fabwu** [comment]
:+1: but which is best practice to access the service manager?

**Comment by ojhaujjwal** [comment]
Don't inject service manager directly to the service. Please inject the missing dependency via factory. I guess you are familiar with that.

**Comment by fabwu** [comment]
I think the best solution is to use the ServiceLocatorAwareInterface or should I inject via constructor?

**Comment by ojhaujjwal** [comment]
No inject via constructor. It is not a good idea to inject service manager to every where. We should only inject dependencies using factory. That is the whole point of using factories.
